kind: Service
apiVersion: v1
metadata:
  name: crudapiweb-service
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 31000
      targetPort: 3000
      protocol: TCP
  selector:
    app: crudapiweb